security:
    enable_authenticator_manager: true
    password_hashers:
        App\Entity\User: 'auto' # Targeting User entity directly
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username # Assuming we use username for login
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: login
                check_path: login
                enable_csrf: true # Ensure CSRF protection is enabled for the login form
            logout:
                path: logout
                target: homepage # Adjust as necessary
    access_control:
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/register, roles: PUBLIC_ACCESS }
        # Secure other paths as necessary
